# Generated by Django 4.1 on 2022-08-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_accounts_bio_accounts_birthdate_accounts_is_critic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="bio",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="is_critic",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="accounts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
