# Generated by Django 4.1 on 2022-08-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("authtoken", "0003_tokenproxy"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("reviews", "0001_initial"),
        ("accounts", "0003_alter_accounts_bio_alter_accounts_is_critic_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Accounts",
            new_name="Account",
        ),
    ]
